fix: removed unnecessary endpoints
hawtio/hawtio-integration pull request #134
Opened 2022-03-31 16:40 UTC by prahaladhchandrahasan

2022-03-31 16:49 UTC, prahaladhchandrahasan commented
I have removed unnecessary endpoints from `Loggers` and `Health` tab. The github workflow is failing for `Trace` tab

2022-04-01 04:47 UTC, tadayosi requested changes

2022-04-01 04:47 UTC, tadayosi commented on plugins/spring-boot/spring-boot.service.spec.ts
> +      workspace.treeContainsDomainAndProperties.and.returnValues(false, false, false, false,false);
insert space: `false,false` -> `false, false`

2022-04-01 04:47 UTC, tadayosi commented on plugins/spring-boot/health/health.service.ts
> +      const mbean: EndpointMBean = this.springBootService.getEndpointMBean(['Health'], ['getData', 'health'])
you should also remove `getData`

2022-04-01 04:47 UTC, tadayosi commented on plugins/spring-boot/loggers/loggers.service.ts
> +      const mbean: EndpointMBean = this.springBootService.getEndpointMBean(['Loggers'], ['getLoggers', 'loggers'])
you should also remove `getLoggers`

2022-04-01 04:47 UTC, tadayosi commented on plugins/spring-boot/loggers/loggers.service.ts
> +      const mbean: EndpointMBean = this.springBootService.getEndpointMBean(['Loggers'], ['setLogLevel', 'configureLogLevel'])
you should also remove `setLogLevel`

2022-04-01 07:03 UTC, closed without merging